version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: rectifex_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=rectifex
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=rectifex_db
    ports:
      - "5432:5432"
    restart: unless-stopped

  backend:
    container_name: rectifex_backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: poetry run uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://rectifex:secret@db:5432/rectifex_db
    depends_on:
      - db
    restart: unless-stopped

  frontend:
    container_name: rectifex_frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
    command: ["npm", "run", "dev"]
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:8000
    restart: unless-stopped

volumes:
  postgres_data: